fix: zig 0.11 (#62)
* build.zig: enable headerpad_max_install_names on MacOs

Fixes error during packing on MacOS with Homebrew:
Error: Failed changing dylib ID of /usr/local/Cellar/fastfec/0.1.9/lib/libfastfec.dylib
  from @rpath/libfastfec.dylib
    to /usr/local/opt/fastfec/lib/libfastfec.dylib
Error: Failed to fix install linkage

and

  Error: Failed changing install name in /opt/homebrew/Cellar/fastfec/0.1.9/bin/fastfec
    from /opt/homebrew/opt/pcre/lib/libpcre.1.dylib
      to @@HOMEBREW_PREFIX@@/opt/pcre/lib/libpcre.1.dylib

See https://github.com/ziglang/zig/issues/13388, where this is inspired from

* Updated for changes to zig build system in version 11

* add back preferred optimize mode

* change wasm os target to freestanding to fix missing main symbol error

* feat: update zig version in github actions workflows

* chore: remove jira ticket from template

* chore: std=gnu99

* chore: unistd for isatty

* chore: include unistd always

* chore: pin python version, update wheel

* chore: attempt to fix python wheel

* chore: remove reproducible wheel

* chore: os-specific python setup

* chore: log lib

* chore: blanket ls

* chore: zig cache ls

* chore: add verbosity

* fix: update zig in requirements-dev

* chore: zig 0.11.0 everywhere else

* chore: revert setup change

* chore: remove test cmds from workflow

* chore: 3.11

---------

Co-authored-by: Michka Popoff <michkapopoff@gmail.com>
Co-authored-by: James Christensen <james.christensen@washpost.com>